### PR TITLE
Refactor entry point to support dependency injection

### PR DESCRIPTION
**Pull request by Balletie**
Related to issues #43 and #45.

This commit defines a new abstract class, `DynSemEntryPoint`, which is responsible for instantiating the Polyglot VM with the proper dependencies: a parser, specification term, and a term registry.

The dependencies are injected by passing them as "configuration" to the VM builder (see `PolyglotEngine.Builder#config`). The configuration parameters are then retrieved when creating the `DynSemContext` in `DynSemLanguage#createContext`.

This allows to inject ones own "parsers", for example a parser which does not parse, but just returns an `ATerm`. Thus an entry point can be created which evaluates `ATerm`s instead of just program source code (see issue #43).

### CODE REVIEW

**Comment by vvergu** [comment]
I haven't yet had the chance to test, but this looks good. Thanks. Do you know whether it will work in combination with a custom `RuleRegistry` as can be optionally specified in the _dynsem.properties_ file (example: https://github.com/MetaBorgCube/metaborg-sl/blob/master/org.metaborg.lang.sl/dynsem.properties#L15)?

**Comment by Balletie** [comment]
@vvergu I replaced injecting a specification term with injecting a rule registry in 3ad59b2.

**Comment by Balletie** [comment]
In commit 2f76237 I changed the file lookup so that it looks in the classpath for the specification term and parse table, rather than the working directory.

This should make the entrypoint more reusable, since any project that includes the generated interpreter (e.g. as a jar) can now work with those files despite being run in a different directory.

**Comment by Balletie** [comment]
@vvergu Commit f9903b8 is a refactoring that results in a number of improvements:
1. Parsing is now completely separate from a generated subclass of DynSemLanguage.
2. Because of 1., providing an entry point for ASTs is trivial, since the interpreter can now be called directly with ITerms. (issue #43)
3. Any rule can now be invoked by a client that has the generated interpreter in the classpath. Previously this was only possible with the "init" rule.

See the very long commit message for more details. I have tested it and it works for me.

**Comment by Balletie** [comment]
The last 5 commits (05fa326 through 96fdf39) resulted from trying this branch out on the [SimpleLanguage](https://github.com/MetaBorgCube/metaborg-sl) and running its tests.

**Comment by vvergu** [comment]
@Balletie can you update the PR with the latest changes in master please? Then we can go ahead with the merge. Thanks.

**Comment by Balletie** [comment]
I merged with the latest master.

**Comment by Balletie** [comment]
@vvergu I also changed the generation of the launch configuration so that it launches from the new main class. So now it's fully up-to-date with master.

**Comment by vvergu** [comment]
I've tried it on SIMPL and everything seems fine. Thanks for the good work and thanks for you contribution. Much appreciated.

Can you comment on #43 with instructions on how one can call the interpreter on an ATerm instead of a file.

**Comment by Balletie** [comment]
@vvergu I created a new PR (#60) which adds an entry point for ATerms. Let me know if the instructions given in the description are sufficient.

**Comment by vvergu** [comment]
Thanks @Balletie, let's move discussion to #60 and #43. PR closed & locked.

**Pull request merged**
